### ISSUE TITLE
Codespacesを起動すると rails: command not found が表示されてしまう

### ISSUE THREAD

**Issue by tzwada** [yasslab/codespaces-railstutorial#11]
この railstutorial のテンプレートページから、説明に沿って利用しようとしたところ、図のように rails: command not found とエラーが出ます。
<img width="650" alt="スクリーンショット 2024-02-08 12 29 33" src="https://github.com/yasslab/codespaces-railstutorial/assets/7919609/fb4e0c6e-222f-431f-9892-2eaee65b81c4">

私の理解では、このテンプレートにてRailsのインストールも行われるのであって、自前でRailsインストールは不要だと思うのです。

なにか設定がおかしいのでしょうか。

**Comment by yasulab** [comment]
@tzwada ご報告ありがとうございます! 🙏✨
今手元でも同じ現象を確認できたので、原因を調査しておきますね 👀💨

📹 再現動画: https://gyazo.com/5a16f05cc00764d0dcac8dc512db3979

**Comment by yasulab** [comment]
GitHub Codespaces 内部で使われているRubyのバージョンが 3.2.2 -> 3.2.3 に更新されたのが原因のようですね :eyes: 💭 本リポジトリもそれに合わせて更新しますが、一旦は Ruby のバージョンを 3.2.3 にしていただくと進められるかなと思います! 😆👌

**Comment by yasulab** [comment]
@tzwada 先ほど更新して手元では動くことを確認したので、もう一度試してみていただけると幸いです...!! 🛠💨✨ (関連するエラーメッセージも後ほど対応する予定ですが、一旦動くところまではできたかなと思います!)

<img width="331" alt="image" src="https://github.com/yasslab/codespaces-railstutorial/assets/155807/30a2b56e-4ec3-42eb-8983-fc9dc561ce98">

<img width="1476" alt="image" src="https://github.com/yasslab/codespaces-railstutorial/assets/155807/63722944-574f-40d1-8130-242421bd93bf">

**Comment by yasulab** [comment]
こちら直ったことが確認できたので一旦 Close しますが、もしまた同じ現象があったら再度 Re-open していただければ...!! 🙏 ✨

**Comment by tzwada** [comment]
私も修正されたことを確認しました。
早速の対応ありがとうございました！（感謝）

**Comment by yasulab** [comment]
いえいえ！無事に直ったようでよかったです！😆👌✨
