### ISSUE TITLE
Codespaces環境構築中にターミナルでbash: rails: command not foundと表示される

### ISSUE THREAD

**Issue by rina-ke** [yasslab/codespaces-railstutorial#16]
初めまして(issue立てるの初めてで、書き方間違ってたらすみません)
https://github.com/yasslab/codespaces-railstutorial/issues/11 と同様の現象だと思います

## error内容
`Created codespace on main`クリック後の環境構築の自動実行中に
```
$ rails server
bash: rails: command not found
```
と表示される。

## 原因調査
出力を確認すると
`Bundler::RubyVersionMismatch: Your Ruby version is 3.2.4, but your Gemfile specified 3.2.3`
とありversionの違いのよう

`.devcontainer/devcontainer.json`にある

> // https://github.com/devcontainers/images/tree/main/src/ruby
  "image": "mcr.microsoft.com/devcontainers/ruby:3.2",

の部分を確認するとパッチバージョンが更新されていた
https://github.com/devcontainers/images/blob/main/src/ruby/history/1.1.4.md#variant-32-bookworm

## 解決方法（の一つ）
Gemfileにある

> ruby "3.2.3"

を`ruby "3.2.4"`に変更後、ページ更新もしくは
```
bundle install
rails server
```
を実行するとロゴ画像が表示される

**Comment by rakuda-san-desu** [comment]
@Nya-ku ご報告ありがとうございます！
詳しいdescriptionもいただきとても助かります🙏✨

手元でも同じ現象を確認しましたので、これから調査・対応していきますね👍
![スクリーンショット 2024-05-01 10 14 55](https://github.com/yasslab/codespaces-railstutorial/assets/41533420/9d35dc3a-2515-49e3-a293-f30568fecd59)

**Comment by rakuda-san-desu** [comment]
@Nya-ku いただいたご報告を元に調査を行い、先ほど修正が完了しました！
詳しいご報告のおかげでとてもスムーズに作業できました。ありがとうございます😌✨

🔽 対応完了後
<img width="1023" alt="スクリーンショット 2024-05-01 11 39 26" src="https://github.com/yasslab/codespaces-railstutorial/assets/41533420/b3902823-7919-49fc-baba-e5f871f4bf8c">

問題解決を確認できたので一旦 Close します🛠
また何か気になる点などありましたら、その際も issue などでお気軽にお知らせいただけると嬉しいです🙏✨

**Comment by rina-ke** [comment]
よかったです
早速の対応ありがとうございました！
